version: '3.9'

services:
  postgres:
    image: docker.io/amd64/postgres:14-alpine
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  jaeger:
    image: quay.io/jaegertracing/all-in-one:latest
    environment:
        COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "${JAEGER_WEBUI_PORT:-18686}:16686"
      - "${OTLP_EXPORTER_PORT:-4317}:4317"
